#
# Smart Meter Texas 2.0 for Home Assistant using command_line sensor with cURL
#
# Originally from https://github.com/mrand/smart_meter_texas/
#
# Step 1: submit an on-demand request to SMT.  This returns a correlationId, which is used in step 2
#
- platform: command_line
  name: Smart Meter Request
  value_template: '{{ value_json.correlationId }}'
  json_attributes:     # These are not strictly necessary.  Could be useful for status and/or debug
    - statusReason
    - statusCode
    - trans_id
    - errorMessage
  scan_interval: 3600  # SMT blocks request any faster/lower than 1800 (twice an hour).
  command: !secret smart_meter_curl_request
#
#
# Step 2: use the correlationId provided above to read the results of the above request.
#         Usually isn't immediately available after step 1... might take a minute or more.
#
# Note: at HA bootup, the below sensor might return and error about invalid correlationId
#         because the correlationId sensor above hasn't been initalized yet.  
#         It always seems to quickly resolve itself.
#
#  value_template: '{{ value_json.smart_meter_read_json.odrRead }}'
- platform: command_line
  name: Smart Meter Read
  unit_of_measurement: kWh
  value_template: '{{ value_json.odrRead.registeredRead }}'
  json_attributes:      # These are not strictly necessary.  Could be useful for status and/or debug
    - correlationId     # This is the correlationId returned by this status read. Should match the Id from sensor.smar
t_meter_request
    - statusReason
    - statusCode
    - errorMessage
    - odrRead
  scan_interval: 900   # Much lower doesn't make sense since we can only read once every 30 minutes
  command: !secret smart_meter_curl_read
